version: "3.8"

services:
  krakend:
    image: devopsfaith/krakend
    # The below line allows us to connect the
    # docker's localhost to the host's localhost
    # for example host.docker.internal:8090
    # allows us to connect 127.0.0.1:8090
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    restart: always
    container_name: ${PROJECT_NAME}
    ports:
      - "${GATEWAY_PORT}:8080"
    environment:
      - KRAKEND_CONFIG=src/krakend.json
      - FC_ENABLE=1
      - FC_SETTINGS=${SOURCE_DIR}/settings
      - API_KEY=${API_KEY}
    volumes:
      - ./src:${SOURCE_DIR}
